name: Generate Contribution Snake

on:
  schedule: 
    - cron: "0 0 * * *"
  workflow_dispatch:
  push: 
    branches: 
      - master
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate GitHub Contribution Snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: github-snake.svg

      - name: List files in dist directory
        run: ls -al dist/

      - name: Upload generated files as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: snake-artifacts
          path: dist/
